#!/usr/bin/env bash
# Build the sidecar locally and join the edge node. No image registry.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# shellcheck disable=SC1091
source "$ROOT/resolve-ipc-dir.sh"
if ! resolve_ipc_checkout "$ROOT"; then
  echo "ERROR: MQTT CA not found next to this checkout." >&2
  echo "The edge node is already running in its own directory. This sidecar only needs that directory's data/mqtt/certs/ca.crt." >&2
  echo "Looked under:" >&2
  printf '%s\n' "$IPC_LOOKED" >&2
  echo "Expected sibling: ../nexus-asset-example-docker-dev (the git clone name)." >&2
  echo "If the edge checkout lives elsewhere: IPC_DIR=/path/to/that/checkout ./up.sh" >&2
  exit 1
fi
export IPC_DIR IPC_MQTT_CERTS_DIR

if [[ ! -f robot_control/adeept_rasptank2/web/app.py ]]; then
  echo "ERROR: vendor web tree missing. Clone with: git clone --recurse-submodules" >&2
  exit 1
fi

./prepare.sh

if [[ -z "$(grep -E '^MQTT_PASSWORD=' .env | head -1 | cut -d= -f2- | tr -d '\r\"')" ]]; then
  echo "ERROR: MQTT_PASSWORD is still empty in .env" >&2
  exit 1
fi

set_key() {
  local key="$1"
  local val="$2"
  if grep -qE "^${key}=" .env; then
    sed -i "s|^${key}=.*|${key}=${val}|" .env
  else
    echo "${key}=${val}" >> .env
  fi
}

# Join the edge stack. Do not copy the host MQTT URL (127.0.0.1) into this container.
set_key IPC_MQTT_CERTS_DIR "$IPC_MQTT_CERTS_DIR"
set_key ANX_BRIDGE_ENABLED true
set_key MQTT_BROKER "mqtts://mqtt:8883"
set_key MQTT_USER anx
set_key MQTT_CA_FILE "/certs/ca.crt"
set_key IPC_DOCKER_NETWORK anx-assets-ipc-network
set_key ANX_TOPIC_PREFIX rasptank
# Upright shoulder rest (stock mid 90° holds arm forward and overheats the servo).
set_key ANX_ARM_REST_DEG 180

# Self-signed TLS for https://:5000 and wss://:8888 (stock UI requires wss on HTTPS pages).
TLS_DIR="${ROBOT_TLS_DIR:-$ROOT/data/certs}"
mkdir -p "$TLS_DIR"
if [[ ! -f "$TLS_DIR/robot.key" || ! -f "$TLS_DIR/robot.crt" ]]; then
  if ! command -v openssl >/dev/null 2>&1; then
    echo "ERROR: openssl is required to generate the robot UI TLS certificate" >&2
    exit 1
  fi
  HOSTNAME_FQDN="$(hostname -f 2>/dev/null || hostname || echo localhost)"
  HOSTNAME_SHORT="$(hostname -s 2>/dev/null || echo localhost)"
  # Include common LAN addresses so browsers accept the cert for the Pi IP.
  SAN="DNS:localhost,DNS:${HOSTNAME_SHORT},DNS:${HOSTNAME_FQDN},IP:127.0.0.1"
  while read -r ip; do
    [[ -n "$ip" ]] || continue
    SAN="${SAN},IP:${ip}"
  done < <(hostname -I 2>/dev/null | tr ' ' '\n' | head -8)
  echo "Generating self-signed TLS cert (${TLS_DIR}/robot.crt) SAN=${SAN}"
  openssl req -x509 -newkey rsa:2048 -sha256 -nodes -days 825 \
    -keyout "$TLS_DIR/robot.key" \
    -out "$TLS_DIR/robot.crt" \
    -subj "/CN=${HOSTNAME_SHORT}/O=ANX Robot Sidecar" \
    -addext "subjectAltName=${SAN}"
  chmod 640 "$TLS_DIR/robot.key" "$TLS_DIR/robot.crt" || true
fi
set_key ANX_ROBOT_TLS true
set_key ANX_ROBOT_TLS_CERT /certs/tls/robot.crt
set_key ANX_ROBOT_TLS_KEY /certs/tls/robot.key
set_key ROBOT_TLS_DIR "$TLS_DIR"

# lgpio opens /dev/gpiochip*. The PCA9685 motors use /dev/i2c-*.
# Picamera2/libcamera need /dev/video* /dev/media* /dev/dma_heap* (and /run/udev
# from docker-compose.yml). privileged does not put those nodes in the container.
{
  echo "# Generated by up.sh from host device nodes. Do not commit."
  echo "services:"
  echo "  anx-robot:"
  echo "    devices:"
  shopt -s nullglob
  gpio=0
  i2c=0
  cam=0
  for dev in \
    /dev/gpiochip* /dev/i2c-* /dev/gpiomem /dev/spidev* \
    /dev/video* /dev/media* /dev/dma_heap /dev/dma_heap* \
    /dev/vchiq /dev/vcsm /dev/vcsm-cma /dev/dri/card* /dev/dri/render*
  do
    [[ -e "$dev" ]] || continue
    echo "      - ${dev}:${dev}"
    [[ "$dev" == /dev/gpiochip* ]] && gpio=1
    [[ "$dev" == /dev/i2c-* ]] && i2c=1
    [[ "$dev" == /dev/video* || "$dev" == /dev/media* ]] && cam=1
  done
  shopt -u nullglob
} > docker-compose.devices.yml

if [[ "$gpio" -ne 1 || "$i2c" -ne 1 ]]; then
  echo "ERROR: the sidecar container cannot drive the HAT without the Pi device nodes." >&2
  [[ "$gpio" -eq 1 ]] || echo "  missing /dev/gpiochip* (liblgpio opens these)" >&2
  [[ "$i2c" -eq 1 ]] || echo "  missing /dev/i2c-* (PCA9685). Enable I2C, then reboot: sudo raspi-config nonint do_i2c 0" >&2
  exit 1
fi
if [[ "$cam" -ne 1 ]]; then
  echo "WARNING: no /dev/video* or /dev/media* on the host — Picamera2 will see 0 cameras." >&2
  echo "  Enable the camera (raspi-config / dtoverlay), check the ribbon cable, then re-run ./up.sh." >&2
fi
echo "Container device nodes:"
sed -n 's/^      - //p' docker-compose.devices.yml

docker compose -f docker-compose.yml -f docker-compose.devices.yml up -d --build

echo "Devices visible inside the container:"
docker exec anx-robot-sidecar sh -c 'ls -l /dev/gpiochip* /dev/i2c-* /dev/video* /dev/media* 2>/dev/null || true'
echo "liblgpio in the image:"
docker exec anx-robot-sidecar sh -c 'ldconfig -p | grep liblgpio'
echo "libcamera cameras inside the container:"
docker exec anx-robot-sidecar python -c 'from picamera2 import Picamera2; print(Picamera2.global_camera_info())' || true

PORT="$(grep -E '^ROBOT_HTTP_PORT=' .env | head -1 | cut -d= -f2- || true)"
PORT="${PORT:-5000}"
echo ""
echo "Robot sidecar is up (image built locally, no registry)."
echo "Health: curl -sk https://127.0.0.1:${PORT}/health"
echo "UI: https://<pi-ip>:${PORT}/  Control WSS: wss://<pi-ip>:8888  (login admin:123456)"
echo "Browser will warn on the self-signed cert from data/certs/robot.crt — that is expected."
echo "Use https:// only (not http://) so the UI and WSS are not mixed-content blocked."
if curl -sk --connect-timeout 3 "https://127.0.0.1:${PORT}/health" >/dev/null 2>&1; then
  echo "HTTPS health OK."
  curl -sk "https://127.0.0.1:${PORT}/health" || true
  echo
else
  echo "WARNING: https://127.0.0.1:${PORT}/health not reachable yet — check: docker logs anx-robot-sidecar"
fi
echo "Pair the edge node with any one method: manual ZIP, USB, Bluetooth, or pairing link."
